"""This module stores colors used by sheets, translations, and others"""

from .sheets import DEFAULT_COLOR

WHITE = 0xffffff
FIREBRICK = 0xB22222
CORAL = 0xFF7F50
ORANGE = 0xBDB76B
KHAKI = 0xF0E68C

WHITESPACE_CELL_COLOR = ORANGE
WHITESPACE_ROW_COLOR = DEFAULT_COLOR
DUPLICATE_CELL_COLOR = FIREBRICK
DUPLICATE_ROW_COLOR = DEFAULT_COLOR
